# Generated by Django 5.0.3 on 2024-10-12 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('horario', models.ManyToManyField(help_text='Seleccione un horario para esta clase', to='catalog.horario')),
            ],
        ),
        migrations.CreateModel(
            name='ClaseInstancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este hueco de la clase', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('d', 'Disponible'), ('r', 'Reservada')], default='d', help_text='Estado del hueco de la clase', max_length=1)),
                ('clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.clase')),
            ],
        ),
    ]
