# Generated by Django 5.0.3 on 2024-10-13 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_clase_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claseinstancia',
            name='alumno',
            field=models.ForeignKey(blank=True, help_text='Alumno que reserva este hueco', limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claseinstancia',
            name='horario',
            field=models.ForeignKey(help_text='Horario asignado para esta instancia de la clase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.horario'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10, null=True),
        ),
    ]
