# Generated by Django 5.0.3 on 2024-10-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_clase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'permissions': [('puede_gestionar_clases', 'Puede gestionar las clases'), ('puede_ver_reservas_profesor', 'Puede ver las reservas de los alumnos en las clases del profesor'), ('puede_realizar_reservas', 'Puede realizar reservas'), ('puede_ver_reservas_alumno', 'Puede ver sus reservas que ha hecho')]},
        ),
    ]
