# Generated by Django 5.0.3 on 2024-10-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_horario_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='horario',
            field=models.ManyToManyField(to='catalog.horario'),
        ),
    ]
